services:
  api:
    image: groupride-api
    build:
      context: backend
      dockerfile: dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/groupride

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
